# global variables of the pipeline

container: container/bioinfo_preproc.sif
samples: samples_info.tsv
ref_fasta: ref_genome/mg10.scaffolds.fa
threads: 4

mosdepth_window: 100
mosdepth_threads: 4

java_heap_mem: 4

coverage_quantile: 0.95
