# global variables of the pipeline

container: containers/miniforge3_extended.sif
samples: config/samples_info.tsv
ref_fasta: resources/GCA_036588685.1_MT.fa

threads: 16

hiseq_rg1: "L001"
hiseq_rg2: "L002"

novaseq_rg1: "AH52GLDSXX"
novaseq_rg2: "AH52HJDSXX"

# fastp global parameters
fastp_complexity_threshold: 20
fastp_P: 100
adapter_fasta: resources/adapters.fa

# Memory parameters in Gb
gatk_java_heap_mem: 8

# Quality config
mosdepth_threads: 4
java_heap_mem: 4
coverage_quantile: 0.99
