# global variables of the pipeline

container: containers/preprocessing_container.sif
samples: config/samples_info.tsv
ref_fasta: results/GCA_019925275.1/GCA_019925275.1_PEIMed_genomic.fna

threads: 16

hiseq_rg1: "L001"
hiseq_rg2: "L002"

novaseq_rg1: "AH52GLDSXX"
novaseq_rg2: "AH52HJDSXX"

# fastp global parameters
fastp_complexity_threshold: 20
fastp_P: 100
adapter_fasta: resources/adapters.fa

# bwa parameters
# bwa_k: 15
# bwa_B: 4
# bwa_O: 4
# bwa_L: 5

# Memory parameters in Gb
gatk_java_heap_mem: 8

# Quality config
mosdepth_threads: 4
java_heap_mem: 4
coverage_quantile: 0.99
