# global variables of the pipeline

container: container/preprocessing_container.sif
samples: resources/samples_info.tsv
ref_fasta: ref_genome/mgal_01.fa
mito_ref: resources/mito_ref/mitoF_ref.fa
mito_ref_gb: resources/mito_ref/mitoF_ref.gb

threads: 28

hiseq_rg1: "L001"
hiseq_rg2: "L002"

novaseq_rg1: "AH52GLDSXX"
novaseq_rg2: "AH52HJDSXX"

# fastp global parameters
fastp_complexity_threshold: 20
fastp_P: 100
adapter_fasta: resources/adapters.fa

# bwa parameters
bwa_k: 10
bwa_B: 4
bwa_O: 4
bwa_L: 5

# Memory parameters in Gb
gatk_java_heap_mem: 8

# Quality config
mosdepth_threads: 4
java_heap_mem: 4
coverage_quantile: 0.99

# Mitochondrial genes to extract
mito_genes:
  - CYTB
  - COX2
  - ND1
  - ND4
  - COX3
  - ND2
  - ND3
  - ATP8
  - COX1
  - ATP6
  - ND4L
  - ND5
  - ND6
  - rrnS
  - rrnL