# global variables of the pipeline

container: containers/preprocessing_container.sif
samples: resources/samples_info.tsv
ref_fasta: resources/ref_genome/mgal_02.fa

threads: 28

hiseq_rg1: "L001"
hiseq_rg2: "L002"

novaseq_rg1: "AH52GLDSXX"
novaseq_rg2: "AH52HJDSXX"

# fastp global parameters
fastp_complexity_threshold: 20
fastp_P: 100
adapter_fasta: resources/adapters.fa

# bwa parameters
bwa_k: 10
bwa_B: 4
bwa_O: 4
bwa_L: 5

# Memory parameters in Gb
gatk_java_heap_mem: 8

# Quality config
mosdepth_threads: 4
java_heap_mem: 4
coverage_quantile: 0.99
